user情報をbigqueryで取得
Greek-Academy/sql-digeon pull request #17
Opened 2024-10-02 12:11 UTC by 8894asa

![Uploading スクリーンショット 2024-10-02 17.24.00.png…]()

2024-10-02 12:38 UTC, silenvx requested changes

2024-10-02 12:38 UTC, silenvx commented on api/bigquery/user.ts
> +import { getConfig } from "@/config";
このファイルを定義する場所は
api/src/repository
がよいです
mysqlもここにおいてます

2024-10-02 12:38 UTC, silenvx commented on api/bigquery/user.ts
> +  async create(users: User[]): Promise<void> {
試してないですがいけるんですかね？
権限ないならエラー返していいかなと

2024-10-02 12:38 UTC, silenvx commented on api/src/index.ts
> +    const {BigQuery} = require('@google-cloud/bigquery');
requireではなくimportがよいです

2024-10-03 13:07 UTC, 8894asaasa commented on api/bigquery/user.ts
> +  async create(users: User[]): Promise<void> {
すみません, どういう意味でしょうか

2024-10-03 13:10 UTC, silenvx commented on api/bigquery/user.ts
> +  async create(users: User[]): Promise<void> {
テーブル名とか指定してないのでそもそも動くのかなと

2024-10-03 16:29 UTC, silenvx approved these changes

2024-10-03 16:30 UTC, merged